language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

branches:
  only:
    - source

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

before_script:
  - composer install --prefer-dist

script:
  - sh build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && sh publish.sh

env:
  global:
    - secure: "ErrsQw5DrnXLALwWIIeE5o1eyrF0iSogx6Ym/eO8pkXf65cY1QwYG+1TK53nsbAWBq0AXpUymO9AGCtYWsC8Ct3QHodImBcgDh0DEVbRvJXdl/XgOcJzAa6XLgfK1NDmMW4QYQUjFIPjoXeoL0naXN/IpQbKZcIfoFmdjclza8Y="
