title: Jakub Zalas
permalink: /:title
paginate: 10
paginate_path: "blog/page:num"
url:
    main: http://jakzal.github.io/zalas.eu
    assets: http://jakzal.github.io/zalas.eu
author:
    name: Jakub Zalas
pygments: true
