title: Jakub Zalas
description: Jakub Zalas Blog
permalink: /:title
paginate: 5
paginate_path: "blog/page:num"
url:
    main: ''
    feed: 'http://zalas.eu'
    assets: ''
author:
    name: Jakub Zalas
    email: jakub@zalas.pl
disqus:
    shortname: zalas
    url: 'http://www.zalas.eu'
analytics:
    google: UA-607315-8
    verify: PBznb5+bhxbUdD7HvioYYudpqitFdLDgjQTv8SwALq4=
pygments: true
exclude: ["vendor"]
