title: Jakub Zalas
subtitle: Agile Software Engineer

url: http://zalas.eu

google_analytics_tracking_id: 'UA-607315-8'
google_verify: 'PBznb5+bhxbUdD7HvioYYudpqitFdLDgjQTv8SwALq4='

disqus:
    shortname: zalas